name: DCO Check (sandbox)

on: [pull_request]

jobs:
  dco:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Verify Signed-off-by line(s)
        shell: bash
        run: |
          missing=""
          while read -r sha; do
            if ! git log -1 --format=%B "$sha" | grep -q '^Signed-off-by:'; then
              missing="$missing $sha"
            fi
          done < <(git log --pretty=format:%H ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
          if [ -n "$missing" ]; then
            echo "::error title=DCO validation failed::Commit(s) missing Signed-off-by:$missing"
            exit 1
          fi

